### ISSUE TITLE
cd same line

### ISSUE THREAD

**Issue by trinker** [kbroman/minimal_make#2]
I'm learning to use make (haven't actually tied it yet) because I saw how nicely you outline it and it made me want to try.  I saw you write:

> One oddity: if you need to change directories to run a command, do the cd on the same line as the related command. The following _would not work_:

```
### this doesn't work ###
Figs/fig1.pdf: R/fig1.R
    cd R
    R CMD BATCH fig1.R fig1.Rout
```

I saw in Yihui's knitr package he has a make file but put's them (cd and next command) on separate lines.  He puts a `;\` after the cd command though.  

https://github.com/yihui/knitr/blob/master/Makefile

Do you think this might work?:

```
Figs/fig1.pdf: R/fig1.R
    cd R;\
    R CMD BATCH fig1.R fig1.Rout
```

**Comment by kbroman** [comment]
Ah, yes. I hadn't thought of that.

\ is for a continuation line at the shell, so I guess it works in make, too. make treats the two lines as if they were really one line. Note that the semi-colon is still necessary in this case.
