### ISSUE TITLE
Link to Software Carpentry lesson is broken

### ISSUE THREAD

**Issue by simonthelwall** [kbroman/minimal_make#6]
Hi, 
The link to the lesson (http://software-carpentry.org/v4/make/index.html) returns a 404 for me, should the link now be http://swcarpentry.github.io/make-novice/ ?

**Comment by kbroman** [comment]
[Fixed](https://github.com/kbroman/minimal_make/commit/26bc3a167363bddecad54b22c63ee091b9975742), thanks!
