### ISSUE TITLE
Consider drake

### ISSUE THREAD

**Issue by wlandau-lilly** [kbroman/minimal_make#7]
The [drake package](https://github.com/wlandau-lilly/drake) is an R-focused version of Make, and it may be a better fit for some research projects. The toy workflow in [one of the vignettes](https://wlandau-lilly.github.io/drake/articles/application.html) is an example. If the same project were to use Make with the same set of targets, it would spend more time initializing R sessions than doing actual work.

By the way, I love the blog post that corresponds to this repo, and I share it all the time.

**Comment by kbroman** [comment]
Cool! I [added a link to drake](https://github.com/kbroman/minimal_make/commit/52c13198bb46c2ad0195feace8a9a9100040bded).

**Comment by kbroman** [comment]
I decided I should also [add drake](https://github.com/kbroman/minimal_make/commit/2a43bc9c3e8e078c21ebfcd24b50bdc49e810630) to the bullet points in the Resources section, so it doesn't get lost.

**Comment by wlandau-lilly** [comment]
Fantastic, @kbroman! Thank you very much!
